In [13]:
Wang_Science2025_top50 = read.csv("/dssg/home/acct-svetoslav_chakarov/svetoslav_chakarov/Data/External_Data/Wang_Science2025_mouse_human/analysis_mouse/Wang_Science2025_mouse_adipose_top50_DE_genes.csv")
Wang_Science2025_top50 <- Wang_Science2025_top50 %>%
  group_by(group) %>%
  mutate(DE_rank = row_number()) %>%
  ungroup()

In [2]:
head(Wang_Science2025_top50)

  group names   scores   logfoldchanges pvals pvals_adj
1 APC   Gsn     182.9771 5.831226       0     0
2 APC   Adamts5 180.6057 6.367613       0     0
3 APC   Clec3b  178.9315 6.081959       0     0
4 APC   Tnxb    176.0929 5.179954       0     0
5 APC   Celf2   175.9112 3.258359       0     0
6 APC   Nid1    175.3835 4.862360       0     0

In [3]:
Xenium_panel = read.csv("/dssg/home/acct-svetoslav_chakarov/svetoslav_chakarov/Lab_members/Yanan_Hu/YNH_Xenium/adipose_analysis/Xenium_final_479_gene_annotation_table.csv")

In [4]:
head(Xenium_panel)

  gene          ensembl_gene_id    panel_origin             probe_sets
1 0610005C13Rik ENSMUSG00000109644 Original mMulti v1 panel 6
2 1110017D15Rik ENSMUSG00000028441 Original mMulti v1 panel 7
3 2610528A11Rik ENSMUSG00000096001 Original mMulti v1 panel 8
4 5330417C22Rik ENSMUSG00000040412 Original mMulti v1 panel 8
5 6330403K07Rik ENSMUSG00000018451 Original mMulti v1 panel 8
6 A330076H08Rik ENSMUSG00000109321 Original mMulti v1 panel 8
  codewords tissues         source_cell_types
1 1         Kidney          epithelial cell of proximal tubule
2 1         Lung            ciliated columnar cell of tracheobronchial tree
3 1         Large Intestine enterocyte of epithelium of large intestine
4 1         Pancreas        pancreatic A cell
5 1         Lung            pulmonary interstitial fibroblast
6 1         Pancreas;Brain  pancreatic A cell;GABAergic neuron
  eos_category eos_common eos_short_lived eos_long_lived canonical_marker
1              False      False           False          False
2              False      False           False          False
3              False      False           False          False
4              False      False           False          False
5              False      False           False          False
6              False      False           False          False
  canonical_cell_type canonical_marker_group canonical_direction
1
2
3
4
5
6
  canonical_use_policy
1
2
3
4
5
6

In [23]:
Xenium_panel[grep("Adipose", Xenium_panel$tissues),]

    gene    ensembl_gene_id    panel_origin             probe_sets codewords
53  Car3    ENSMUSG00000027559 Original mMulti v1 panel 8          1
54  Cav1    ENSMUSG00000007655 Original mMulti v1 panel 8          1
63  Cd3d    ENSMUSG00000032094 Original mMulti v1 panel 8          1
71  Cfh     ENSMUSG00000026365 Original mMulti v1 panel 8          1
104 Ctse    ENSMUSG00000004552 Original mMulti v1 panel 8          1
105 Ctsg    ENSMUSG00000040314 Original mMulti v1 panel 8          1
119 Dpt     ENSMUSG00000026574 Original mMulti v1 panel 8          1
126 Epsti1  ENSMUSG00000022014 Original mMulti v1 panel 8          1
155 Gpihbp1 ENSMUSG00000022579 Original mMulti v1 panel 8          1
162 Hemgn   ENSMUSG00000028332 Original mMulti v1 panel 8          1
164 Hmbs    ENSMUSG00000032126 Original mMulti v1 panel 8          1
175 Igfbp6  ENSMUSG00000023046 Original mMulti v1 panel 5          1
182 Iyd     ENSMUSG00000019762 Original mMulti v1 panel 8          1
205 Lum     ENSMUSG00000036446 Original mMulti v1 panel 8          1
216 Mgll    ENSMUSG00000033174 Original mMulti v1 panel 8          1
222 Mpo     ENSMUSG00000009350 Original mMulti v1 panel 8          1
238 Nbl1    ENSMUSG00000041120 Original mMulti v1 panel 8          1
254 Pcolce2 ENSMUSG00000015354 Original mMulti v1 panel 8          1
289 Retn    ENSMUSG00000012705 Original mMulti v1 panel 8          1
290 Retnla  ENSMUSG00000061100 Original mMulti v1 panel 8          1
293 Rhd     ENSMUSG00000028825 Original mMulti v1 panel 8          1
350 Timp3   ENSMUSG00000020044 Original mMulti v1 panel 8          1
    tissues
53  Bladder Lumen;Adipose Tissue
54  Lymph Node;Adipose Tissue
63  Mammary Gland;Adipose Tissue;Kidney;Lung;Limb Muscle;Spleen;Skin of Body
71  Heart;Adipose Tissue
104 Bone Marrow;Adipose Tissue;Spleen;Large Intestine
105 Kidney;Adipose Tissue
119 Adipose Tissue
126 Mammary Gland;Adipose Tissue;Kidney;Lung;Limb Muscle;Spleen;Skin of Body
155 Adipose Tissue
162 Bone Marrow;Adipose Tissue;Spleen;Large Intestine
164 Bone Marrow;Adipose Tissue;Spleen
175 Lymph Node;Adipose Tissue
182 Adipose Tissue;Trachea;Large Intestine
205 Adipose Tissue
216 Adipose Tissue
222 Kidney;Adipose Tissue
238 Bladder Lumen;Adipose Tissue
254 Lung;Adipose Tissue
289 Adipose Tissue
290 Adipose Tissue;Lung
293 Bone Marrow;Adipose Tissue;Spleen
350 Kidney;Lung;Adipose Tissue
    source_cell_types
53  bladder cell;mesenchymal stem cell of adipose tissue
54  valve lymphatic endothelial cell;endothelial cell
63  T cell;T cell;T cell;T cell;T cell;T cell;T cell
71  endocardial cell;mesenchymal stem cell of adipose tissue
104 erythroblast;erythroblast;erythroblast;large intestine goblet cell
105 lymphocyte;lymphocyte
119 mesenchymal stem cell of adipose tissue
126 T cell;T cell;T cell;T cell;T cell;T cell;T cell
155 endothelial cell
162 erythroblast;erythroblast;erythroblast;hematopoietic stem cell large
164 erythroblast;erythroblast;erythroblast
175 valve lymphatic endothelial cell;mesenchymal stem cell of adipose tissue
182 epithelial cell;epithelial cell;epithelial cell of large intestine
205 mesenchymal stem cell of adipose tissue
216 endothelial cell
222 lymphocyte;lymphocyte
238 bladder cell;mesenchymal stem cell of adipose tissue
254 adventitial cell;mesenchymal stem cell of adipose tissue
289 myeloid cell
290 myeloid cell;lung macrophage
293 erythroblast;erythroblast;erythroblast
350 kidney cortex artery cell;adventitial cell;mesenchymal stem cell of adipose tissue
    eos_category eos_common eos_short_lived eos_long_lived canonical_marker
53               False      False           False          False
54               False      False           False          False
63               False      False           False          True
71               False      False           False          False
104              False      False           False          False
105              False      False           False          True
119              False      False           False          True
126              False      False           False          False
155              False      False           False          True
162              False      False           False          False
164              False      False           False          False
175              False      False           False          False
182              False      False           False          False
205              False      False           False          True
216              False      False           False          False
222              False      False           False          True
238              False      False           False          False
254              False      False           False          True
289              False      False           False          True
290              False      False           False          False
293              False      False           False          False
350              False      False           False          False
    canonical_cell_type canonical_marker_group canonical_direction
53
54
63  T_cell              t_cell                 POSITIVE
71
104
105 Neutrophil          neutrophil             POSITIVE
119 Stromal_fibroblast  stromal_fibroblast     POSITIVE
126
155 Endothelial         vascular_endothelial   POSITIVE
162
164
175
182
205 Stromal_fibroblast  stromal_fibroblast     POSITIVE
216
222 Neutrophil          neutrophil             POSITIVE
238
254 Stromal_fibroblast  stromal_fibroblast     POSITIVE
289 Adipocyte           adipocyte              POSITIVE
290
293
350
    canonical_use_policy
53
54
63  PRIMARY_SUPPORT
71
104
105 PRIMARY_SUPPORT
119 PRIMARY_SUPPORT
126
155 PRIMARY_SUPPORT
162
164
175
182
205 PRIMARY_SUPPORT
216
222 PRIMARY_SUPPORT
238
254 PRIMARY_SUPPORT
289 PRIMARY_SUPPORT
290
293
350

In [14]:
library(dplyr)

Wang_Science2025_top50_Xenium <- Wang_Science2025_top50 %>%
  inner_join(
    Xenium_panel,
    by = c("names" = "gene")
  ) %>%
  arrange(group, DE_rank)

In [15]:
dim(Wang_Science2025_top50_Xenium)

[1] 144  22

In [16]:
marker_coverage <- Wang_Science2025_top50 %>%
  group_by(group) %>%
  summarise(
    n_top50 = n(),
    n_in_Xenium = sum(names %in% Xenium_panel$gene),
    fraction_in_Xenium = n_in_Xenium / n_top50,
    .groups = "drop"
  ) %>%
  arrange(desc(fraction_in_Xenium))

marker_coverage

   group       n_top50 n_in_Xenium fraction_in_Xenium
1  Eosinophil  50      19          0.38
2  Macrophage  50      13          0.26
3  Monocyte    50      13          0.26
4  Neutrophil  50      13          0.26
5  MHCIIhi     50      10          0.20
6  Endothelial 50       9          0.18
7  Mast cell   50       6          0.12
8  MatureAdip  50       6          0.12
9  T           50       6          0.12
10 Mesothelial 50       5          0.10
11 NK          50       5          0.10
12 Plasma      50       5          0.10
13 APC         50       4          0.08
14 B           50       4          0.08
15 DC          50       4          0.08
16 Epithelial  50       4          0.08
17 cDC1        50       4          0.08
18 ILC2        50       3          0.06
19 Low-quality 50       3          0.06
20 Pericyte    50       3          0.06
21 γδ T        50       3          0.06
22 pDC         50       2          0.04
23 Germ cell   50       0          0.00

In [17]:
Wang_Xenium_marker_list <- Wang_Science2025_top50_Xenium %>%
  group_by(group) %>%
  summarise(
    markers = paste(names, collapse = ", "),
    n_markers = n(),
    .groups = "drop"
  )

In [18]:
Wang_Xenium_marker_list

   group
1  APC
2  B
3  DC
4  Endothelial
5  Eosinophil
6  Epithelial
7  ILC2
8  Low-quality
9  MHCIIhi
10 Macrophage
11 Mast cell
12 MatureAdip
13 Mesothelial
14 Monocyte
15 NK
16 Neutrophil
17 Pericyte
18 Plasma
19 T
20 cDC1
21 pDC
22 γδ T
   markers
1  Htra3, Dpt, Lum, Mfap5
2  Lyn, Fau, Rpl18a, Rps13
3  Basp1, Cytip, Adam8, Rab8b
4  Mgll, Cd36, Gpihbp1, Cav1, Kdr, Cavin2, Gng11, Aqp7, S1pr1
5  Srgn, Cd24a, F5, Ccl6, Ccl9, Ptprc, Ccr3, Elmo1, Laptm5, Alox5ap, Cybb, Adgre1, Itgam, Lcp1, Mctp1, Gsr, Pim1, Basp1, Alox15
6  Rps26, Fxyd4, Fau, Krt19
7  Il1rl1, Emb, Coro2a
8  Rpl37a, Retnla, Pf4
9  Laptm5, Trerf1, Ptprc, Camk1d, Ctss, Dock8, Lyn, Coro1a, Itgam, Kctd12
10 Pf4, Adgre1, Ccl6, F13a1, Ccl9, Mctp1, Ctss, Cybb, Ptafr, Laptm5, C5ar1, Folr2, Alox5ap
11 Cpa3, Srgn, Il1rl1, Cyp11a1, Plek, Basp1
12 Car3, Retn, Cav1, Hp, Taldo1, Ppp1r1a
13 Upk3b, Upk1b, Krt19, Cav1, Igfbp6
14 Cybb, Lyn, Cebpb, Ptprc, Itgal, Lst1, Coro1a, Cytip, Gsr, Cd300a, Ctss, Cd44, Lcp1
15 Ptprc, Epsti1, Rac2, Itgal, Satb1
16 Csf3r, Srgn, Mxd1, Gsr, Cxcr2, Taldo1, Lcp1, Cd44, Mmp9, Ptprc, Pglyrp1, Alox5ap, Coro1a
17 Rgs5, Timp3, Aspn
18 Sdc1, Cd24a, Isg20, Pim1, Prg2
19 Cd3d, Ptprc, Rac2, Coro1a, Elmo1, Cytip
20 Plbd1, Mpeg1, Cd24a, Psmb8
21 Runx2, Mpeg1
22 Emb, S100a4, Cd3d
   n_markers
1   4
2   4
3   4
4   9
5  19
6   4
7   3
8   3
9  10
10 13
11  6
12  6
13  5
14 13
15  5
16 13
17  3
18  5
19  6
20  4
21  2
22  3